name: testworkflowreuable
on: 
  workflow_call:
  workflow_dispatch:

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: checout source code
        uses: actions/checkout@v3
        
      - name: Test shell commands
        run: |
          echo "welcome to test workflow"
          ls -lart
          echo "displaying the files in the runner"
        
  
